services:
  app101apipy:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    container_name: app101apipy
    environment:
      APP_ENV: local
      APP101_LOG_FILE: /var/log/app101/app.log
      # SQLALCHEMY_DATABASE_URI: postgresql://app101:password@app101postgres:5432/app101db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    hostname: app101apipy
    image: app101/apipy:latest
    ports:
      - mode: ingress
        target: 5000
        published: 5000
        protocol: tcp
    restart: unless-stopped
